import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Rohan",
      email: "rtrtech20@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Thomas",
      email: "ttvettuparambil@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Rahul Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 1200,
      countInStock: 20,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "High quaity product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 1399,
      countInStock: 13,
      brand: "Adidas",
      rating: "4.0",
      numReviews: 19,
      description: "High quaity product",
    },
    {
      name: "Puma Slim Shirt",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 1149,
      countInStock: 12,
      brand: "Puma",
      rating: "4.5",
      numReviews: 16,
      description: "High quaity product",
    },
    {
      name: "Buffalo formal pants",
      category: "Pants",
      image: "/images/product-4.jpg",
      price: 999,
      countInStock: 10,
      brand: "Buffalo",
      rating: "4.5",
      numReviews: 10,
      description: "High quaity product",
    },
    {
      name: "Puma Slim pants",
      category: "Pants",
      image: "/images/product-5.jpg",
      price: 949,
      countInStock: 20,
      brand: "Puma",
      rating: "4.0",
      numReviews: 14,
      description: "High quaity product",
    },
    {
      name: "Knighthood formal pants",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 1199,
      countInStock: 0,
      brand: "Knighthood",
      rating: "5.0",
      numReviews: 12,
      description: "High quaity product",
    },
  ],
};

export default data;
